### ISSUE TITLE
Support Coursier

### ISSUE THREAD

**Issue by crypticmind** [jrudolph/sbt-dependency-graph#105]
There's an Ivy replacement SBT plugin called [Coursier](https://github.com/alexarchambault/coursier) which sbt-dependency-graph cannot work with.

```
java.lang.IllegalStateException: sbt-dependency-graph plugin currently only supports InlineConfiguration of ivy settings (the default in sbt)
	at net.virtualvoid.sbt.graph.Plugin$.crossName(Plugin.scala:206)
	at net.virtualvoid.sbt.graph.Plugin$$anonfun$graphSettings$2$$anonfun$apply$1.apply(Plugin.scala:71)
	at net.virtualvoid.sbt.graph.Plugin$$anonfun$graphSettings$2$$anonfun$apply$1.apply(Plugin.scala:71)
	at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$1.apply(Plugin.scala:88)
	at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$1.apply(Plugin.scala:88)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:ivyReport) java.lang.IllegalStateException: sbt-dependency-graph plugin currently only supports InlineConfiguration of ivy settings (the default in sbt)
```

How possible/desirable would it be to support this plugin?

**Comment by crypticmind** [comment]
As an addendum, Coursier supports the `coursierDependencyTree` command.

**Comment by jrudolph** [comment]
Yes, I think it could still make sense to support coursier. Do you have an example project I could try, which throws the above error message?

**Comment by crypticmind** [comment]
I'll craft a small example project and post it here.

**Comment by crypticmind** [comment]
I got this error because I was using an old version (0.7.4). With 0.8.2 the graphs appear as expected. At this point I don't think a test project is necessary, but in any case, just using version 0.7.4 triggers this error.

**Comment by jrudolph** [comment]
Ok, glad that it works out of the box. :)
