### ISSUE TITLE
dependencyTree doesn't work in sbt 1.1.6 version

### ISSUE THREAD

**Issue by JustYuxinWu** [jrudolph/sbt-dependency-graph#153]
``` scala
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
```

``` scala
sbt.version = 1.1.6
```

My project is multi sbt project.

when i used command `project {subProjectId}` then `dependencyTree`,it run out 

```
sbt:ouros_jobs> project api
[info] Set current project to ouros_api (in build file:/Users/skinny/ZAData/ouros/)
[ouros_api] $ dependencyTree
[info] Updating ProjectRef(uri("file:/Users/skinny/ZAData/ouros/"), "api")...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* com.google.guava:guava:22.0 is selected over {12.0.1, 19.0}
[warn] 	    +- com.typesafe.play:play_2.11:2.6.12                 (depends on 22.0)
[warn] 	    +- com.google.inject:guice:4.1.0                      (depends on 19.0)
[warn] 	    +- org.apache.hbase:hbase-common:1.2.0                (depends on 12.0.1)
[warn] 	    +- org.apache.hbase:hbase-client:1.2.0                (depends on 12.0.1)
[warn] 	* org.scala-lang.modules:scala-java8-compat_2.11:0.8.0 is selected over 0.7.0
[warn] 	    +- com.typesafe.play:play-ahc-ws-standalone_2.11:1.1.6 (depends on 0.8.0)
[warn] 	    +- com.typesafe.play:play_2.11:2.6.12                 (depends on 0.7.0)
[warn] 	    +- com.typesafe.akka:akka-actor_2.11:2.5.11 ()        (depends on 0.7.0)
[warn] 	    +- com.typesafe.play:play-streams_2.11:2.6.12         (depends on 0.7.0)
[warn] 	* com.typesafe.akka:akka-stream_2.11:2.5.11 is selected over {2.5.9, 2.4.20}
[warn] 	    +- com.typesafe.play:play-streams_2.11:2.6.12         (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-http-core_2.11:10.0.11 ()   (depends on 2.4.20)
[warn] 	    +- com.typesafe.play:play-ws-standalone_2.11:1.1.6    (depends on 2.5.9)
[warn] 	* com.typesafe.akka:akka-actor_2.11:2.5.11 is selected over 2.4.20
[warn] 	    +- com.typesafe.play:play_2.11:2.6.12                 (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-stream_2.11:2.5.11 ()       (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-slf4j_2.11:2.5.11 ()        (depends on 2.5.11)
[warn] 	    +- com.typesafe.akka:akka-parsing_2.11:10.0.11 ()     (depends on 2.4.20)
[warn] Run 'evicted' to see detailed eviction warnings
[error] scala.MatchError: 1.0 (of class java.lang.String)
[error] 	at net.virtualvoid.sbt.graph.DependencyGraphSettings$.$anonfun$ivyReportForConfig$8(DependencyGraphSettings.scala:56)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / moduleGraph) scala.MatchError: 1.0 (of class java.lang.String)
[error] Total time: 10 s, completed 2018-6-5 16:26:31```
```

when i used command `dependencyTree` for another sub project,it run out 

```
[info] Set current project to ouros_jobs (in build file:/Users/skinny/ZAData/ouros/)
sbt:ouros_jobs> dependencyTree
[error] scala.MatchError: 1.0 (of class java.lang.String)
[error] 	at net.virtualvoid.sbt.graph.DependencyGraphSettings$.$anonfun$ivyReportForConfig$8(DependencyGraphSettings.scala:56)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / moduleGraph) scala.MatchError: 1.0 (of class java.lang.String)
[error] Total time: 1 s, completed 2018-6-5 16:28:12
```
how to make this command work?

**Comment by jrudolph** [comment]
Hi @JustYuxinWu. Thanks for the report (and sorry for the delay). Can you post an example project exhibiting the problem? It seems for your project `sbtVersion` is set to `"1.0"` instead of to the full sbt version. In my tests the plugin still seems to work with sbt 1.1.6.

Can you post the output of `show sbtVersion`?

**Comment by JustYuxinWu** [comment]
You are right.
I have set the `sbtVersion` to `1.0` somewhere else, witch caused this issue. 
Sorry for wasting your time and I will close this issue later.
Thanks for you help 🙏

**Comment by jrudolph** [comment]
Glad, you solved it :)
