### ISSUE TITLE
ArrayIndexOutOfBoundsException when using dependency-graph --force

### ISSUE THREAD

**Issue by analytically** [jrudolph/sbt-dependency-graph#19]
```
> last compile:dependency-graph
java.lang.RuntimeException: Problem drawing segment EdgeSegment(Point(17,31),Down,Point(18,31)) in edge EdgeDrawingElement(List(Point(5,147), Point(7,147), Point(7,63), Point(17,63), Point(17,31), Point(18,31), Point(18,7), Point(56,7)),false,true)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$com$github$mdr$ascii$layout$Renderer$$render$4.apply(Renderer.scala:122)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$com$github$mdr$ascii$layout$Renderer$$render$4.apply(Renderer.scala:113)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at com.github.mdr.ascii.layout.Renderer.com$github$mdr$ascii$layout$Renderer$$render(Renderer.scala:113)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$render$1.apply(Renderer.scala:158)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$render$1.apply(Renderer.scala:156)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at com.github.mdr.ascii.layout.Renderer.render(Renderer.scala:156)
    at com.github.mdr.ascii.layout.Renderer$.render(Renderer.scala:72)
    at com.github.mdr.ascii.layout.Layouter$.renderGraph(Layout.scala:14)
    at net.virtualvoid.sbt.graph.IvyGraphMLDependencies$.asciiGraph(IvyGraphMLDependencies.scala:94)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4$$anonfun$apply$5.apply(Plugin.scala:77)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4$$anonfun$apply$5.apply(Plugin.scala:77)
    at sbt.MultiLogger.log(MultiLogger.scala:31)
    at sbt.Logger$class.info(Logger.scala:98)
    at sbt.AbstractLogger.info(Logger.scala:11)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4.apply(Plugin.scala:77)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4.apply(Plugin.scala:75)
    at sbt.Scoped$$anonfun$hf3$1.apply(Structure.scala:579)
    at sbt.Scoped$$anonfun$hf3$1.apply(Structure.scala:579)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 62
    at com.github.mdr.ascii.layout.Renderer$Grid.update(Renderer.scala:85)
    at com.github.mdr.ascii.layout.Renderer.com$github$mdr$ascii$layout$Renderer$$drawLine(Renderer.scala:102)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$com$github$mdr$ascii$layout$Renderer$$render$4.apply(Renderer.scala:120)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$com$github$mdr$ascii$layout$Renderer$$render$4.apply(Renderer.scala:113)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at com.github.mdr.ascii.layout.Renderer.com$github$mdr$ascii$layout$Renderer$$render(Renderer.scala:113)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$render$1.apply(Renderer.scala:158)
    at com.github.mdr.ascii.layout.Renderer$$anonfun$render$1.apply(Renderer.scala:156)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at com.github.mdr.ascii.layout.Renderer.render(Renderer.scala:156)
    at com.github.mdr.ascii.layout.Renderer$.render(Renderer.scala:72)
    at com.github.mdr.ascii.layout.Layouter$.renderGraph(Layout.scala:14)
    at net.virtualvoid.sbt.graph.IvyGraphMLDependencies$.asciiGraph(IvyGraphMLDependencies.scala:94)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4$$anonfun$apply$5.apply(Plugin.scala:77)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4$$anonfun$apply$5.apply(Plugin.scala:77)
    at sbt.MultiLogger.log(MultiLogger.scala:31)
    at sbt.Logger$class.info(Logger.scala:98)
    at sbt.AbstractLogger.info(Logger.scala:11)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4.apply(Plugin.scala:77)
    at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$4$$anonfun$apply$4.apply(Plugin.scala:75)
    at sbt.Scoped$$anonfun$hf3$1.apply(Structure.scala:579)
    at sbt.Scoped$$anonfun$hf3$1.apply(Structure.scala:579)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
```

**Comment by samthebest** [comment]
This is a show stopper for me using this tool

**Comment by jrudolph** [comment]
@samthebest why is this a showstopper? The only thing that doesn't work is generating the ASCII graph which isn't a good idea for a big dependency structure anyway. Wouldn't the alternatives like `dependency-tree` or dot output work for you?

**Comment by samthebest** [comment]
@jrudolph Ah, sorry, I didn't realize the alternatives wouldn't throw that exception.  Please could you add a catch for that AIOB and say something along the lines of "Your graph is too big for ASCII version".

**Comment by jrudolph** [comment]
Also see #56 for another reproduction.
