### ISSUE TITLE
Instructions for scala 2.11?

### ISSUE THREAD

**Issue by yonran** [jrudolph/sbt-dependency-graph#94]
What is the recommended way to use this plugin for scala 2.11? I apologize for the noob question.

With [this build.sbt](http://www.scala-sbt.org/0.13/docs/Hello.html):

```scala
organization := "com.example.myorg"

lazy val root = (project in file(".")).
  settings(name := "hello",
  version := "1.0",
  scalaVersion := "2.11.7"
)
```

and this ~/.sbt/plugins.sbt:

```scala
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
```

I get the following output:
```
> sbtVersion
[info] 0.13.11
> compile
[info] Updating {file:/Users/yonran/scratch/sbtproject/}root...
[info] Resolving net.virtual-void#sbt-dependency-graph;0.8.2 ...
[warn] 	module not found: net.virtual-void#sbt-dependency-graph;0.8.2
[warn] ==== local: tried
[warn]   /Users/yonran/.ivy2/local/net.virtual-void/sbt-dependency-graph/scala_2.11/sbt_0.13/0.8.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.11_0.13/0.8.2/sbt-dependency-graph-0.8.2.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.11, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.11, sbtVersion=0.13) (/Users/yonran/.sbt/0.13/plugins.sbt#L10-11)
[warn] 		  +- hello:hello_2.11:1.0
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[error] Total time: 1 s, completed Mar 11, 2016 12:17:24 AM
```

**Comment by jrudolph** [comment]
Try putting the line into `~/.sbt/0.13/plugins/plugins.sbt` (if you put it into `~/.sbt/plugins.sbt` it will be used as a dependency to your code instead of as a dependency to your build).

**Comment by yonran** [comment]
That worked. Thank you so much!

**Comment by shijinkui** [comment]
I can't work.

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: net.virtual-void#sbt-dependency-graph;0.8.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		  +- default:dataflow-server-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
at xsbt.boot.Using$.withResource(Using.scala:10)
at xsbt.boot.Using$.apply(Using.scala:9)
at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
at xsbt.boot.Locks$.apply0(Locks.scala:31)
at xsbt.boot.Locks$.apply(Locks.scala:28)
at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
at sbt.IvySbt.withIvy(Ivy.scala:128)
at sbt.IvySbt.withIvy(Ivy.scala:125)
at sbt.IvySbt$Module.withModule(Ivy.scala:156)
at sbt.IvyActions$.updateEither(IvyActions.scala:168)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1488)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1484)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1519)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1517)
at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1516)
at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
at sbt.Classpaths$.cachedUpdate(Defaults.scala:1539)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1466)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1418)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
at sbt.std.Transform$$anon$4.work(System.scala:63)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.Execute.work(Execute.scala:237)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
```

**Comment by jrudolph** [comment]
Hi @shijinkui, are there any more error message? There should be lines that show which URLs were tried to find the artifact. Can you post them as well? It could also be related to a corruption of the ivy cache. **If you know what you are doing** you could try deleting this directory `~/.ivy2/cache/scala_2.10/sbt_0.13/net.virtual-void/sbt-dependency-graph/` and see if it helps.

**Comment by exaspace** [comment]
Hi @jrudolph on a new project I got "unresolved dependency" also and I can't seem to find the plugin in any public repo - I've looked in bintray, mvnrepo etc. and I've only found very old versions. Can you tell me which is the canonical repository that this plugin is published to please?

**Comment by pwebbitrs** [comment]
@jrudolph I am having this very same issue as @exaspace  ... just can't seem to find the plugin for recent scala versions anywhere.  Thanks.

**Comment by jrudolph** [comment]
It's here: http://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.10_0.13/

There's no version for Scala 2.11 because there are no sbt versions that use Scala 2.11. Can you show the exact error message you got, @pwebbitrs, and how you configured the plugin?

**Comment by mvallebr** [comment]
in my sbt I have `scalaVersion := "2.11.8"` -> this makes sbt look for the artifact in new scala locations. I also cannot find the plugin.

Adding the line
```scala
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
```

to my build.sbt generates the following error messages:

```

[info] Updating ...
[warn] 	module not found: net.virtual-void#sbt-dependency-graph;0.9.2
[warn] ==== local: tried
[warn]   /Users/marcelo.valle/.ivy2/local/net.virtual-void/sbt-dependency-graph/scala_2.11/sbt_1.0/0.9.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.11_1.0/0.9.2/sbt-dependency-graph-0.9.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/marcelo.valle/.sbt/preloaded/net.virtual-void/sbt-dependency-graph/0.9.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/marcelo.valle/.sbt/preloaded/net/virtual-void/sbt-dependency-graph_2.11_1.0/0.9.2/sbt-dependency-graph-0.9.2.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/Users/marcelo.valle/.m2/repository/net/virtual-void/sbt-dependency-graph_2.11_1.0/0.9.2/sbt-dependency-graph-0.9.2.pom
[warn] ==== ICM: tried
[warn]   http://maven.icm.edu.pl/artifactory/repo/net/virtual-void/sbt-dependency-graph_2.11_1.0/0.9.2/sbt-dependency-graph-0.9.2.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: net.virtual-void#sbt-dependency-graph;0.9.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

Please see bellow the URLs it attempted to find.

This is a blocker for me, I would like to use the plugin, but I just can't.

I also tried adding, instead:

```scala
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph_2.10_0.13" % "0.9.2")
```

then it also didn't find, trying the following locations:
```

[warn] ==== local: tried
[warn]   /Users/marcelo.valle/.ivy2/local/net.virtual-void/sbt-dependency-graph_2.10_0.13/scala_2.11/sbt_1.0/0.9.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.10_0.13_2.11_1.0/0.9.2/sbt-dependency-graph_2.10_0.13-0.9.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/marcelo.valle/.sbt/preloaded/net.virtual-void/sbt-dependency-graph_2.10_0.13/0.9.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/marcelo.valle/.sbt/preloaded/net/virtual-void/sbt-dependency-graph_2.10_0.13_2.11_1.0/0.9.2/sbt-dependency-graph_2.10_0.13-0.9.2.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/Users/marcelo.valle/.m2/repository/net/virtual-void/sbt-dependency-graph_2.10_0.13_2.11_1.0/0.9.2/sbt-dependency-graph_2.10_0.13-0.9.2.pom
[warn] ==== ICM: tried
[warn]   http://maven.icm.edu.pl/artifactory/repo/net/virtual-void/sbt-dependency-graph_2.10_0.13_2.11_1.0/0.9.2/sbt-dependency-graph_2.10_0.13-0.9.2.pom
```

**Comment by jrudolph** [comment]
Hi @mvallebr,

> in my sbt I have `scalaVersion := "2.11.8"`

Where did you put that line? You cannot put such a line into `project/xyz.sbt` because each sbt version comes with a fixed Scala version and changing the Scala version for the project build will break things (like you observed here but that will not be the only thing).

If you want to compile your own project with Scala 2.11 put the line into an sbt file in the root of your project.

**Comment by mvallebr** [comment]
the line *is* in the `build.sbt` file in the root of my project

**Comment by mvallebr** [comment]
I cannot change `~/.sbt/0.13/plugins/plugins.sbt` - the build runs remotelly, I have no access to this file. 
Isn't it possible then to use the plugin by changing only my project file?

**Comment by jrudolph** [comment]
> the line _is_ in the `build.sbt` file in the root of my project

Ah, so maybe you put `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")` also into that `build.sbt`? That should go to `project/plugins.sbt` (or any other `.sbt` file below `project`. Can you try if that works?

**Comment by jrudolph** [comment]
Great!
